PieTemp/urls.py
from django.urls import path

from collector import views as co_views

urlpatterns = [
    path('', co_views.dashboard_view, name='home'),
    path('settings/', co_views.settings_view, name='settings'),
    path('temperature/', co_views.raw_temp, name='raw temp'),
    path('r/set-mode/<int:mode>/', co_views.set_relay, name='set relay'),
    path('r/get-mode/', co_views.get_relay_status, name='get relay'),
    path('r/toggle/', co_views.switch_relay, name='toggle relay'),
    path('history/', co_views.get_csv_period, name='history'),
    path('json/', co_views.jsonify_statuses, name='json'),
    path('m/clear-log/', co_views.clear_switch_log)
]

collector/models.py
from django.db import models


# Create your models here.


class Settings(models.Model):
    val_key = models.CharField(max_length=128, unique=True)
    value = models.CharField(max_length=4096, null=True)


class Logs(models.Model):
    temp = models.FloatField()
    timedate = models.DateTimeField(auto_now_add=True)
    action = models.CharField(choices=(
        ('0', 'Wyłączono grzejnik'),
        ('1', 'Włączono grzejnik')
    ), max_length=1)

    class Meta:
        ordering = ['-timedate']


class Temps(models.Model):
    temp = models.FloatField()
    timedate = models.DateTimeField(auto_now_add=True)

collector/forms.py
from django.forms import Form, FloatField, NumberInput, DateTimeField, DateTimeInput


class TempsForm(Form):
    t_high = FloatField(widget=NumberInput(attrs={'class': 'form-control'}))
    t_low = FloatField(widget=NumberInput(attrs={'class': 'form-control'}))
    t_high.label = 'Temperatura wyłączania przekaźnika'
    t_low.label = 'Temperatura włączania przekaźnika'


class TimePeriodForm(Form):
    since = DateTimeField(widget=DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}))
    to = DateTimeField(widget=DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}))
    since.label = 'Od'
    to.label = 'Do'

collector/views.py
import datetime
import json
import logging
import threading
from time import sleep

import w1thermsensor
import yaml
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, reverse
from gpiozero.output_devices import LED as Relay

from .forms import TempsForm, TimePeriodForm
from .models import Settings, Logs, Temps

# Hardware objects
relay = Relay(5)
s = w1thermsensor.W1ThermSensor()

# Config objects
logging.basicConfig(filename='temps.csv',
                    format='%(mytime)s;%(message)s;%(temp)s;%(relay_mode)s;%(th_high)s;%(th_low)s', level=240)
# logging.log(level=240, msg='Config message', extra={'mytime': 'Date', 'temp': 'Temp.', 'relay_mode': 'Relay', 'th_high': 'High', 'th_low': 'Low'})
config_file = open('./PieTemp/config.yaml', mode='r')
config_yaml = yaml.load(config_file)
wt_delay = config_yaml['temp_checker']


# Defining utils and watchdogs
def update_config():
    global config_file
    global config_yaml
    config_file = open('./PieTemp/config.yaml', mode='w+')
    config_file.write(yaml.dump(config_yaml, indent=4, default_flow_style=False))
    config_file = open('./PieTemp/config.yaml', mode='r')


def kget_temp():
    t_high = float(config_yaml['treshold_high'])
    t_low = float(config_yaml['treshold_low'])

    t = s.get_temperature()

    if t > t_high and relay.value == True:
        relay.off()
        log = Logs(temp=t, action='0')
        log.save()
    elif t < t_low and relay.value == False:
        relay.on()
        log = Logs(temp=t, action='1')
        log.save()

    logging.log(level=240, msg='Collected temperature',
                extra={
                    'mytime': datetime.datetime.now().strftime('%Y.%m.%d %H:%M:%S'),
                    'temp': t,
                    'relay_mode': relay.value,
                    'th_high': t_high,
                    'th_low': t_low
                })


def watch_temp():
    while True:
        kget_temp()
        sleep(wt_delay)


# Starting watchdogs
th = threading.Thread(target=watch_temp, name='Watchdog')
th.start()


# Rest of views are here
def dashboard_view(request):
    logs = Logs.objects.all().order_by('-timedate')[:150]
    t_high = float(config_yaml['treshold_high'])
    t_low = float(config_yaml['treshold_low'])
    return render(request, 'dashboard.html', {'logs': logs, 'temps': {'high': t_high, 'low': t_low}})


def raw_temp(request):
    temp = s.get_temperature()

    response = HttpResponse(content=temp, content_type='text/plain')
    return response


def set_relay(request, mode):
    if mode:
        relay.on()
        return HttpResponse(content='Relay is on', content_type='text/plain')
    else:
        relay.off()
        return HttpResponse(content='Relay is off', content_type='text/plain')


def get_relay_status(request):
    return HttpResponse(content=relay.value, content_type='text/plain')


def jsonify_statuses(request):
    temp = s.get_temperature()
    rv = relay.value
    return HttpResponse(
        content=json.dumps(
            {
                'Temperature': temp,
                'Relay switch mode': rv
            }, indent=2
        )
    )


def switch_relay(request):
    relay.toggle()
    return HttpResponse(content='Done', content_type='text/plain', status=201)


def settings_view(request):
    if request.method == 'POST':
        form = TempsForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['t_high'] < form.cleaned_data['t_low']:
                return HttpResponse('FORM IS NOT VALID!!!', status=400)
            else:
                config_yaml['treshold_high'] = form.cleaned_data['t_high']
                config_yaml['treshold_low'] = form.cleaned_data['t_low']

                update_config()
                kget_temp()

                return HttpResponseRedirect(reverse('home'))
        else:
            return HttpResponse('FORM IS NOT VALID!!!', status=400)
    else:
        f = TempsForm(initial={
            't_low': config_yaml['treshold_low'],
            't_high': config_yaml['treshold_high']
        })
        return render(
            request,
            'settings.html',
            {
                'form': f
            }
        )


def show_period(request):
    if request.method == 'POST':
        form = TimePeriodForm(request.POST)
        if form.is_valid():
            temps = Temps.objects.filter(
                timedate__range=(form.cleaned_data['since'], form.cleaned_data['to'])
            ).order_by('-timedate')
            return render(request, 'history.html', {'form': form, 'temps': temps})
        else:
            return render(request, 'history.html', {'form': form})
    else:
        return render(request, 'history.html', {'form': TimePeriodForm()})


def get_csv_period(request):
    response = HttpResponse(content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename="{}.csv"'.format(
        datetime.datetime.now().strftime('%A-%d-%B-%Y')
    )
    with open('temps.csv', mode='r') as rf:
        response.write(rf.read())
    return response

def clear_switch_log(request):
    log = Logs.objects.all()
    k = log.__len__()
    log.delete()
    return HttpResponse(content='Usunięto {} wpisów'.format(k), status=201)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {# Imporitng frontend libs #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <script rel="script" type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script rel="script" type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    {# Block for special links and scripts #}
    {% block special-libs %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-end">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}" title="Panel sterowania"><i class="fas fa-home"></i></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'history' %}" title="Pobierz CSV"><i
                    class="fas fa-clipboard-list"></i> Pobierz CSV</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'settings' %}" title="Ustawienia termostatu"><i
                    class="fas fa-sliders-h"></i> Ustawienia</a>
        </li>
    </ul>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block special-libs %}
    <script src="{% static 'js/data_downloader.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg">
            <h1>Temperatura</h1>
            <p id="temp">Pobieranie danych...</p>
        </div>
        <div class="col-lg">
            <h1>Grzejnik</h1>
            <p>Stan grzejnika: <span id="state" class="badge">Pobieranie danych...</span></p>
        </div>
        <div class="col-lg">
            <h1>Statystyki</h1>
            <p>
                Temp. wł. <span class="badge badge-info">{{ temps.low }} °C</span>
                Temp. wył. <span class="badge badge-danger">{{ temps.high }} °C</span>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg">
            <h1>Logi</h1>
            {% if logs|length == 0 %}
                <p>Nie ma żadnych zapisów</p>
            {% endif %}
            <table class="table table-bordered table-striped">
                <tbody>
                {% for l in logs %}
                    <tr>
                        <th style="width: 35%">
                            {{ l.timedate }}
                        </th>
                        <td style="width: 20%">
                            {{ l.temp }}°C
                        </td>
                        <td class="text-lg-center">
                            {% if l.action == '0' %}
                                <span class="text-info">{{ l.get_action_display }}</span>
                            {% elif l.action == '1' %}
                                <span class="text-danger">{{ l.get_action_display }}</span>
                            {% else %}
                                {{ l.get_action_display }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/history.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary" type="submit">Wyszukaj</button>
            </form>
        </div>
    </div>
    {% if temps|length == 0 %}
        <table class="table table-striped table-bordered">
            <tbody>
            {% for t in temps %}
                <tr>
                    <th>
                        {{ t.timedate }}
                    </th>
                    <td>
                        {{ t.temp }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/settings.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <h1>Ustawienia temperatur</h1>
            <form method="post" novalidate>
                {% csrf_token %}
                <table class="table table-borderless">
                    <tbody>
                    <tr>
                        <th>{{ form.t_high.label }}</th>
                        <td>{{ form.t_high }}</td>
                    </tr>
                    <tr>
                        <th>{{ form.t_low.label }}</th>
                        <td>{{ form.t_low }}</td>
                    </tr>
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">Zapisz</button>
            </form>
        </div>
    </div>
    <div class="row justify-content-center" style="margin-top: 40px">
        <div class="col-lg-7">
            <h1>Czynności konserwacyjne</h1>
            <button id="clearlogs" type="button" class="btn btn-primary">Wyczyść log przełączania grzejnika</button>
        </div>
    </div>
{% endblock %}
{% block special-libs %}
    <script>
        $(document).ready(
            function () {
                $('#clearlogs').click(function () {
                    requestClearingLogs()
                })
            }
        );
        function requestClearingLogs() {
            $.ajax({
                url: '/m/clear-log',
                success: function (status_text) {
                    alert(status_text)
                }
            })
        }
    </script>
{% endblock %}